<div class="page-header">
    <h3>Cidades</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a class="btn btn-info" href="<?php echo $this->url('cidades', array('action' => 'novo')); ?>">
            <span class="glyphicon glyphicon-plus"></span>
            Novo registro
        </a></div>
    <div class="col-md-9">
        <form class="form-inline" role="form" method="post">
            <div class="form-group">
                <label class="sr-only" for="pesquisa">Pesquisar: </label>
                <input type="text" class="form-control" id="pesquisa" 
                       value="<?php echo $term;?>"
                       placeholder="Nome da cidade" name="pesquisa"/>
            </div>
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
                Pesquisar</button>
        </form>


    </div>

</div>
<br/><br/>
<table class="table table-hover table-responsive table-striped">
    <tr>
        <th>Nome</th>
        <th>Editar</th>
        <th>Excluir</th>
    </tr>
    <?php foreach ($paginator as $item): ?>
        <tr>
            <td>
                <?php echo $item->getNome(); ?> -
                <?php echo $item->getUf()->getSigla(); ?>
            </td>
            <td>
                <a href="
                <?php
                echo $this->url('cidades', array(
                    'action' => 'editar',
                    'id' => $item->getId()
                ));
                ?>"
                   >
                    <span class="glyphicon glyphicon-edit"></span>
                    Editar
                </a>
            </td>
            <td>
                <a href="
                <?php
                echo $this->url('cidades', array(
                    'action' => 'excluir',
                    'id' => $item->getId()
                ));
                ?>"
                   onclick="return confirm('Deseja realmente excluir este registro?')"
                   >
                    <span class="glyphicon glyphicon-trash"></span>
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
echo $this
        ->paginationControl(
                $paginator, 'Sliding', 'partial/paginator', array('route' => 'cidades'));
?>